### ISSUE TITLE
Feature request: Only show the bar on mod key down like i3wm

### ISSUE THREAD

**Issue by QiangF** [t-wissmann/barpyrus#22]
For the purpose of saving some screen real estate and keep distractions away, I really like the default bar in i3wm, which is like a float frame and only show on mod key down with this setting:

    bar {
        mode hide
        hidden_state hide
        modifier $mod
        workspace_buttons yes
    }

The bar disappear when mod key is released. It is ideal for laptop with small screens.

**Comment by The-Compiler** [comment]
I don't think this is possible to implement. Barpyrus is a wrapper around [lemonbar](https://wiki.archlinux.org/title/Lemonbar) and other projects, and those would need to support this (but do not, as far as I know).

The only thing that could be done is quitting the bar entirely and restarting it. But you could already do that now, without any new support from barpyrus.
